import type {
  ApprovalItem,
  AgentQueueItem,
  AgentSnapshot,
  CandidateRecord,
  DashboardSummary,
  DomainPackRecord,
  EvolutionArtifactRecord,
  RuntimeCapabilityDriver,
  RuntimeCompilerContract,
  RuntimeEnvironmentAssessment,
  RuntimeExecutionPlan,
  RuntimeEpisode,
  RuntimeEpisodeReplay,
  RuntimePatch,
  RuntimePlanReplanResult,
  RuntimeSnapshot,
  RuntimeTaskSpec,
  RuntimeTemplate,
  RuntimeWorkspaceData,
  SettingsSnapshot,
  SkillRecord,
  SyncBacklogItem,
  SyncStatusSnapshot,
  TimelineEvent,
  WorkflowDefinition,
} from "./types";

const now = new Date();
const iso = (offsetMinutes: number): string => new Date(now.getTime() + offsetMinutes * 60_000).toISOString();

const candidates: CandidateRecord[] = [
  {
    id: "cand-001",
    name: "Mia Chen",
    title: "高级前端工程师",
    platform: "Recruit Agent",
    location: "上海",
    status: "screening",
    workflowNode: "initial_screening",
    jdTitle: "前端平台工程师",
    matchScore: 92,
    experienceYears: 8,
    nextAction: "确认系统设计深度和 React 性能案例是否足够扎实。",
    summary: "产品感觉好、owner 意识清晰，UI 细节和工程深度比较平衡。",
    tags: ["React", "设计系统", "性能优化"],
    resumeAvailable: true,
    lastContactedAt: iso(-120),
  },
  {
    id: "cand-002",
    name: "Jason Li",
    title: "后端工程师",
    platform: "Recruit Agent",
    location: "杭州",
    status: "pending_communication",
    workflowNode: "initiate_communication",
    jdTitle: "平台工程师",
    matchScore: 84,
    experienceYears: 6,
    nextAction: "发送外联消息，并说明薪资范围和团队职责范围。",
    summary: "服务设计经验可靠，对后端运行和交付有较强 owner 意识。",
    tags: ["Go", "PostgreSQL", "接口"],
    resumeAvailable: false,
  },
  {
    id: "cand-003",
    name: "Luna Wang",
    title: "产品经理",
    platform: "Recruit Agent",
    location: "北京",
    status: "cooldown",
    workflowNode: "cooldown",
    jdTitle: "产品负责人",
    matchScore: 73,
    experienceYears: 7,
    nextAction: "尊重冷却期，等下一个联系窗口再评估是否继续。",
    summary: "沟通后已拒绝，先保留在暂停池中，避免重复外联。",
    tags: ["用户洞察", "路线图", "数据分析"],
    resumeAvailable: true,
    cooldownUntil: iso(60 * 24 * 18),
    lastContactedAt: iso(-1440),
  },
];

const workflows: WorkflowDefinition[] = [
  {
    id: "wf-screening",
    name: "发现到初筛",
    jdTitle: "前端平台工程师",
    status: "active",
    version: "v1.3",
    updatedAt: iso(-180),
    nodes: [
      { id: "discover", name: "发现候选人", kind: "discover", status: "approved", owner: "Scheduler", description: "搜索并接入候选人档案。" },
      { id: "initial_screening", name: "初筛", kind: "screen", status: "running", owner: "Agent", description: "阅读简历并按 JD 要求做判断。" },
      { id: "initiate_communication", name: "发起沟通", kind: "communicate", status: "idle", owner: "Agent", description: "使用批准后的消息模板发起外联。" },
      { id: "request_resume", name: "获取简历", kind: "resume", status: "idle", owner: "Agent", description: "收集结构化简历材料。" },
      { id: "candidate_scoring", name: "候选人评分", kind: "score", status: "idle", owner: "Agent", description: "生成评分和判断依据。" },
      { id: "hr_review", name: "HR 审查", kind: "review", status: "blocked", owner: "Human", description: "在同步人才库前等待人工批准。" },
    ],
  },
  {
    id: "wf-talent-pool",
    name: "人才库交接",
    jdTitle: "平台工程师",
    status: "draft",
    version: "v0.8",
    updatedAt: iso(-75),
    nodes: [
      { id: "screen", name: "初筛评分", kind: "screen", status: "approved", owner: "Agent", description: "按标准完成评分。" },
      { id: "talent_pool_upload", name: "上传人才库", kind: "review", status: "idle", owner: "Human", description: "把合格候选人推送到内部系统。" },
    ],
  },
];

const skills: SkillRecord[] = [
  {
    id: "skill-001",
    skillId: "recruit_outreach_drafting",
    name: "招聘外联撰写",
    description: "生成简短、克制、带岗位上下文的外联内容。",
    category: "communication",
    version: "1.2.0",
    status: "active",
    boundNode: "initiate_communication",
    platform: "Recruit Agent",
    inputSchema: { type: "object", required: ["candidate_profile", "jd_context"] },
    outputSchema: { type: "object", required: ["message", "rationale"] },
    riskLevel: "medium",
    skillMetadata: { owner: "recruit-agent", approval_mode: "user_confirm" },
    health: "healthy",
    lastCheckedAt: iso(-30),
    summary: "生成简短、克制、带岗位上下文的外联内容。",
  },
  {
    id: "skill-002",
    skillId: "resume_screening",
    name: "Resume Screening",
    description: "根据 JD 和证据完成结构化初筛。",
    category: "screening",
    version: "1.0.4",
    status: "pending_review",
    boundNode: "initial_screening",
    platform: "Recruit Agent",
    inputSchema: { type: "object", required: ["resume", "jd_requirements", "candidate_memory"] },
    outputSchema: { type: "object", required: ["scorecard", "decision", "evidence_refs"] },
    riskLevel: "medium",
    skillMetadata: { owner: "recruit-agent", approval_mode: "user_confirm" },
    health: "warning",
    lastCheckedAt: iso(-90),
    summary: "由近期候选人案例沉淀而来，当前等待批准。",
  },
  {
    id: "skill-003",
    skillId: "talent_pool_packaging",
    name: "人才库交接打包",
    description: "为后续上传整理候选人资料包和评分摘要。",
    category: "handoff",
    version: "0.9.1",
    status: "degraded",
    boundNode: "candidate_scoring",
    platform: "Recruit Agent",
    inputSchema: { type: "object", required: ["candidate_bundle", "scorecard"] },
    outputSchema: { type: "object", required: ["handoff_payload"] },
    riskLevel: "high",
    skillMetadata: { owner: "recruit-agent", approval_mode: "user_confirm" },
    health: "critical",
    lastCheckedAt: iso(-240),
    summary: "最近一次浏览器运行中检测到选择器漂移。",
  },
];

const approvals: ApprovalItem[] = [
  {
    id: "apr-001",
    kind: "skill",
    title: "批准 Resume Screening Skill",
    detail: "在启用前先审查新的初筛策略。",
    requester: "agent",
    status: "pending",
    createdAt: iso(-45),
    targetType: "skill_draft",
    targetId: "artifact-001",
    payload: {
      artifact_kind: "skill_draft",
      related_skill_id: "skill-002",
      risk_level: "medium",
    },
    surface: "evolution",
    relatedCandidateId: null,
  },
  {
    id: "apr-002",
    kind: "candidate_message",
    title: "确认给 Jason Li 发送首轮沟通消息",
    detail: "Recruit Agent 已起草外联消息，等待人工确认后发送。",
    requester: "recruit-agent",
    status: "pending",
    createdAt: iso(-65),
    surface: "runtime",
    relatedCandidateId: "cand-002",
    payload: {
      candidate_id: "cand-002",
      draft_message: "你好 Jason，我们正在招聘平台工程师，想和你沟通一下岗位细节。",
      blocked_task: { candidate_id: "cand-002", task_type: "initiate_communication" },
    },
  },
  {
    id: "apr-003",
    kind: "system_command",
    title: "允许本地包检查命令",
    detail: "在白名单控制下注册一个安全命令。",
    requester: "agent",
    status: "rejected",
    createdAt: iso(-180),
    surface: "evolution",
    relatedCandidateId: null,
  },
];

export const desktopEvolutionArtifactsMock: EvolutionArtifactRecord[] = [
  {
    id: "artifact-001",
    agentProfileId: "agent-profile-recruit",
    artifactKind: "skill_draft",
    title: "联系方式抽取 skill v3",
    summary: "基于最近 7 天候选人详情页漂移，补了一层联系方式解析和降级策略。",
    status: "pending_review",
    relatedCandidateId: null,
    relatedSkillId: "skill-002",
    proposedBy: "recruit-agent",
    reviewedBy: null,
    reviewedAt: null,
    appliedAt: null,
    artifactBody: {
      current: {
        selector_strategy: ["profile.phone", "profile.wechat"],
        fallback: [],
      },
      proposed: {
        selector_strategy: ["contact.drawer.phone", "contact.drawer.wechat", "profile.phone", "profile.wechat"],
        fallback: ["message_history.signature"],
      },
    },
    artifactMetadata: {
      risk_level: "medium",
      scope: "contact_and_resume",
      source: "runtime_learning",
      evidence_refs: ["episode-002", "detail_surface drift"],
    },
    createdAt: iso(-48),
    updatedAt: iso(-48),
  },
  {
    id: "artifact-002",
    agentProfileId: "agent-profile-recruit",
    artifactKind: "prompt_patch",
    title: "候选人首轮外联口吻修订",
    summary: "把首轮外联语气收紧，减少过度热情和一次性信息量。",
    status: "draft",
    relatedCandidateId: null,
    relatedSkillId: "skill-001",
    proposedBy: "recruit-agent",
    reviewedBy: null,
    reviewedAt: null,
    appliedAt: null,
    artifactBody: {
      current: {
        opening: "你好，我这边在看你的经历，想和你沟通一下机会。",
      },
      proposed: {
        opening: "你好，看到你的经历和当前岗位有一定匹配，想先确认你是否愿意了解岗位信息。",
      },
    },
    artifactMetadata: {
      risk_level: "low",
      scope: "candidate_messaging",
      source: "operator_feedback",
    },
    createdAt: iso(-120),
    updatedAt: iso(-90),
  },
  {
    id: "artifact-003",
    agentProfileId: "agent-profile-recruit",
    artifactKind: "memory_policy_patch",
    title: "Candidate memory 分层压缩策略",
    summary: "候选人会话超过 1M 时自动 compact，并保留 preview/operator/model 三层披露。",
    status: "approved",
    relatedCandidateId: null,
    relatedSkillId: null,
    proposedBy: "recruit-agent",
    reviewedBy: "desktop-user",
    reviewedAt: iso(-180),
    appliedAt: iso(-175),
    artifactBody: {
      current: {
        compact_threshold: 800000,
        tiers: ["preview", "operator_summary"],
      },
      proposed: {
        compact_threshold: 1000000,
        tiers: ["preview", "operator_summary", "model_context"],
        progressive_disclosure: true,
      },
    },
    artifactMetadata: {
      risk_level: "low",
      scope: "candidate_memory",
      source: "manual_design",
    },
    createdAt: iso(-220),
    updatedAt: iso(-175),
  },
  {
    id: "artifact-004",
    agentProfileId: "agent-profile-recruit",
    artifactKind: "playbook_patch",
    title: "多轮面试状态机模板",
    summary: "在默认状态机中补充联系方式、AI/人工评估和多轮面试节点。",
    status: "applied",
    relatedCandidateId: null,
    relatedSkillId: null,
    proposedBy: "desktop-user",
    reviewedBy: "desktop-user",
    reviewedAt: iso(-320),
    appliedAt: iso(-315),
    artifactBody: {
      current: {
        statuses: ["screening", "communication", "resume"],
      },
      proposed: {
        statuses: [
          "profile_reviewed",
          "contact_required",
          "contact_acquired",
          "resume_requested",
          "resume_received",
          "ai_assessment_completed",
          "human_assessment_completed",
          "waiting_schedule_round_1",
          "interview_round_1_scheduled",
          "waiting_schedule_round_2",
          "interview_round_2_scheduled",
          "offer_review",
        ],
      },
    },
    artifactMetadata: {
      risk_level: "medium",
      scope: "workflow_definition",
      source: "manual_design",
    },
    createdAt: iso(-360),
    updatedAt: iso(-315),
  },
];

const agent: AgentSnapshot = {
  status: "running",
  activeTask: "正在为 Mia Chen 执行初筛",
  browserLock: "held",
  uptime: "03:12:41",
  queueDepth: 4,
  tokenBudgetUsed: 38,
  health: "warning",
};

const events: TimelineEvent[] = [
  {
    id: "evt-001",
    label: "候选人阶段已推进",
    detail: "已将 Mia Chen 推进到初筛步骤。",
    at: iso(-12),
    tone: "positive",
  },
  {
    id: "evt-002",
    label: "审批待处理",
    detail: "Resume Screening Skill 正在等待人工审查。",
    at: iso(-32),
    tone: "warning",
  },
  {
    id: "evt-003",
    label: "已应用冷却期",
    detail: "Luna Wang 已被标记为避免重复外联。",
    at: iso(-48),
    tone: "neutral",
  },
];

const alerts: TimelineEvent[] = [
  {
    id: "alert-001",
    label: "检测到选择器漂移",
    detail: "人才库交接打包在恢复完全自动化前需要先刷新。",
    at: iso(-22),
    tone: "critical",
  },
];

const settings: SettingsSnapshot = {
  locale: "en-US",
  timezone: "Asia/Shanghai",
  intranetEnabled: false,
  desktopApprovalsOnly: true,
  skillHealthAutonomyEnabled: false,
  skillHealthAutonomyIntervalSeconds: 300,
  providers: [
    { kind: "openai-compatible", name: "主 OpenAI 接口", model: "gpt-5.4", enabled: true, temperature: 0.2, baseUrl: "https://api.openai.com/v1" },
    { kind: "anthropic", name: "备用 Anthropic 接口", model: "claude-sonnet-4", enabled: false, temperature: 0.2, baseUrl: "https://api.anthropic.com" },
  ],
  platform: {
    name: "Recruit Agent",
    account: "本机场景 01",
    cooldownDays: 18,
    allowOutboundMessaging: false,
    maxConcurrentRuns: 1,
    bossMaxConcurrentRuns: 1,
  },
};

const metrics = [
  { label: "已筛选候选人", value: "126", delta: "+14%", tone: "positive" as const, caption: "过去 7 天" },
  { label: "回复率", value: "41%", delta: "+6%", tone: "positive" as const, caption: "外联到回复" },
  { label: "已用预算", value: "$182", delta: "-9%", tone: "neutral" as const, caption: "本周 Token 支出" },
  { label: "人工审批", value: "3", delta: "1 个待处理", tone: "warning" as const, caption: "人工关卡队列" },
];

const pipeline = [
  { label: "发现", value: 18, target: 20 },
  { label: "初筛", value: 12, target: 16 },
  { label: "沟通", value: 7, target: 10 },
  { label: "评分", value: 4, target: 6 },
  { label: "人工审查", value: 3, target: 4 },
];

export const desktopMockSnapshot: DashboardSummary = {
  metrics,
  pipeline,
  timeline: events,
  alerts,
  candidates,
  workflows,
  skills,
  approvals,
  agent,
  settings,
};

const runtimeTasks: RuntimeTaskSpec[] = [
  {
    id: "task-001",
    title: "筛选前端平台工程师候选人",
    description: "由自然语言需求生成的招聘 Agent 初筛草稿。",
    goal: "找出适合前端平台工程师岗位的候选人，整理评分和下一步建议。",
    domain: "recruiting",
    status: "trial_ready",
    sourceKind: "natural_language",
    sourceText: "帮我筛一批前端平台工程师候选人，整理评分和下一步建议。",
    inputs: {},
    constraints: { requires_human_supervision: true, respect_messaging_approval: true },
    successCriteria: { minimum_candidates: 3, requires_scorecard: true, requires_next_action: true },
    approvalPolicy: { mode: "desktop_review", trial_required: true },
    outputContract: { kind: "candidate_bundle", format: "table" },
    preferredCapabilities: ["search", "browser", "document", "llm", "api"],
    preferredDomains: ["recruiting"],
    compiledPayload: {
      domain_pack: "recruiting",
      compiler_source: "llm",
      compiler_quality: {
        quality_status: "accepted",
        quality_score: 0.94,
        repair_count: 0,
        missing_required_fields: [],
        warnings: [],
      },
      requires_trial: true,
      trial_expectations: { requires_supervised_trial: true, requires_scene_assessment_for_browser: true },
    },
    activePlanId: "plan-001",
    createdAt: iso(-200),
    updatedAt: iso(-120),
  },
  {
    id: "task-002",
    title: "推进 Jason Li 沟通与简历获取",
    description: "围绕单个候选人的沟通推进与简历请求草稿。",
    goal: "确认对 Jason Li 的首轮沟通、请求简历，并记录沟通结果。",
    domain: "recruiting",
    status: "compiled",
    sourceKind: "natural_language",
    sourceText: "帮我推进 Jason Li 的沟通，发出简历请求并整理后续动作。",
    inputs: {},
    constraints: { requires_human_supervision: true, respect_messaging_approval: true },
    successCriteria: { requires_candidate_evidence: true, requires_message_draft: true, requires_next_action: true },
    approvalPolicy: { mode: "desktop_review", trial_required: true },
    outputContract: { kind: "candidate_bundle", format: "markdown" },
    preferredCapabilities: ["browser", "document", "llm", "api"],
    preferredDomains: ["recruiting"],
    compiledPayload: {
      domain_pack: "recruiting",
      compiler_source: "llm",
      compiler_quality: {
        quality_status: "accepted",
        quality_score: 0.9,
        repair_count: 0,
        missing_required_fields: [],
        warnings: [],
      },
      requires_trial: true,
      trial_expectations: { requires_supervised_trial: true, requires_scene_assessment_for_browser: true },
    },
    activePlanId: "plan-002",
    createdAt: iso(-90),
    updatedAt: iso(-60),
  },
];

const runtimePlans: RuntimeExecutionPlan[] = [
  {
    id: "plan-001",
    taskSpecId: "task-001",
    name: "前端平台工程师初筛试跑",
    mode: "trial",
    status: "validated",
    version: 2,
    approvalState: "template_candidate",
    planBody: {
      steps: [
        { id: "discover_candidate", capability: "search" },
        { id: "inspect_candidate_profile", capability: "browser" },
        { id: "summarize_candidate_context", capability: "document" },
        { id: "score_candidate", capability: "llm" },
        { id: "prepare_handoff", capability: "api" },
      ],
      instruction: "筛选前端平台工程师候选人，并整理候选人评分与后续建议。",
      domain: "recruiting",
    },
    environmentRequirements: { requires_browser: true, requires_network: true },
    checkpoints: [{ kind: "approval", label: "复用前先审查候选人评分摘要" }],
    runtimeMetadata: { compiler: "llm", domain_pack: "recruiting" },
    compiledFromPatchId: undefined,
    createdAt: iso(-200),
    updatedAt: iso(-30),
  },
  {
    id: "plan-002",
    taskSpecId: "task-002",
    name: "Jason Li 沟通推进试跑",
    mode: "trial",
    status: "diverged",
    version: 1,
    approvalState: "pending_review",
    planBody: {
      steps: [
        { id: "inspect_candidate_profile", capability: "browser" },
        { id: "draft_outreach_message", capability: "llm" },
        { id: "capture_human_confirmation", capability: "approval" },
        { id: "request_resume", capability: "api" },
      ],
      instruction: "推进 Jason Li 的沟通，并在确认后发出简历请求。",
      domain: "recruiting",
    },
    environmentRequirements: { requires_browser: true, requires_network: true },
    checkpoints: [{ kind: "approval", label: "审查沟通漂移与修订建议" }],
    runtimeMetadata: { compiler: "llm", domain_pack: "recruiting" },
    compiledFromPatchId: undefined,
    createdAt: iso(-90),
    updatedAt: iso(-18),
  },
];

const runtimeEpisodes: RuntimeEpisode[] = [
  {
    id: "episode-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    mode: "trial",
    status: "awaiting_review",
    requestedBy: "desktop-user",
    requiresConfirmation: true,
    startedAt: iso(-70),
    finishedAt: iso(-65),
    resultSummary: "试跑已完成前端候选人初筛，并产出评分摘要与下一步建议。",
    observations: [{ step_id: "inspect_candidate_profile", kind: "observation", summary: "已检查首批候选人卡片、岗位标签和公开档案摘要。" }],
    actions: [{ step_id: "discover_candidate", capability: "search", status: "completed" }],
    metrics: { step_count: 5, completion_rate: 1 },
    divergenceDetected: false,
    patchId: undefined,
    runtimeMetadata: { operator: "desktop-user" },
    createdAt: iso(-70),
    updatedAt: iso(-65),
  },
  {
    id: "episode-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    mode: "trial",
    status: "diverged",
    requestedBy: "desktop-user",
    requiresConfirmation: true,
    startedAt: iso(-24),
    finishedAt: iso(-18),
    resultSummary: "试跑已生成沟通草稿，但候选人详情页状态漂移，需要更新确认节点。",
    observations: [{ step_id: "inspect_candidate_profile", kind: "observation", summary: "候选人详情页把最近沟通记录收进了新的标签页。" }],
    actions: [{ step_id: "draft_outreach_message", capability: "llm", status: "completed" }],
    metrics: { step_count: 4, completion_rate: 1 },
    divergenceDetected: true,
    patchId: "patch-001",
    runtimeMetadata: { operator: "desktop-user" },
    createdAt: iso(-24),
    updatedAt: iso(-18),
  },
];

const runtimeSnapshots: RuntimeSnapshot[] = [
  {
    id: "snapshot-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    executionEpisodeId: "episode-001",
    source: "browser",
    environmentKey: "recruiting:candidate_listing",
    status: "captured",
    url: "https://example.com/recruiting/candidates",
    title: "候选人列表页",
    pageType: "candidate_listing",
    capabilityHints: ["search", "browser"],
    observedEntities: [{ kind: "candidate_card", label: "Mia Chen 候选人卡片" }],
    affordances: [{ kind: "open_candidate", label: "打开候选人详情" }],
    runtimeMetadata: { plan_name: "前端平台工程师初筛试跑" },
    createdAt: iso(-66),
    updatedAt: iso(-66),
  },
  {
    id: "snapshot-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    source: "browser",
    environmentKey: "recruiting:detail_surface",
    status: "captured",
    url: "https://example.com/recruiting/candidates/site_002",
    title: "Jason Li 候选人详情页",
    pageType: "detail_surface",
    capabilityHints: ["browser", "llm"],
    observedEntities: [{ kind: "candidate_workspace", label: "Jason Li 档案" }],
    affordances: [{ kind: "switch_tab", label: "切换到沟通标签" }],
    runtimeMetadata: { plan_name: "Jason Li 沟通推进试跑" },
    createdAt: iso(-18),
    updatedAt: iso(-18),
  },
];

const runtimeCapabilityDrivers: RuntimeCapabilityDriver[] = [
  {
    id: "driver-001",
    key: "browser.navigator",
    name: "浏览器导航器",
    category: "browser",
    status: "ready",
    scope: "在网页场景中完成导航、观察 DOM 状态，并记录受监督操作。",
    description: "当系统需要直接观察页面、点击目标或保留场景截图时，优先使用这个驱动。",
    safetyMode: "supervised_write",
    supportsWrite: true,
    sceneTypes: ["candidate_listing", "detail_surface", "candidate_workspace", "message_thread"],
    signalLabels: ["dom_affordances", "scene_classifier", "selector_confidence"],
    updatedAt: iso(-15),
  },
  {
    id: "driver-002",
    key: "search.discovery",
    name: "搜索发现器",
    category: "search",
    status: "ready",
    scope: "检索公开网络，并把排序后的候选结果送入试跑计划。",
    description: "适用于需要先广泛搜索、再进入浏览器或 HTTP 观察的探索型任务。",
    safetyMode: "read_only",
    supportsWrite: false,
    sceneTypes: ["search_results", "research_seed"],
    signalLabels: ["ranking_score", "source_diversity", "query_rewrite"],
    updatedAt: iso(-22),
  },
  {
    id: "driver-003",
    key: "http.harvest",
    name: "HTTP 采集器",
    category: "http",
    status: "degraded",
    scope: "优先抓取结构化页面或 API，再决定是否升级到浏览器观察。",
    description: "适合可通过轻量请求解决的场景，但当前仍有部分结构漂移需要关注。",
    safetyMode: "read_only",
    supportsWrite: false,
    sceneTypes: ["api_resource", "candidate_workspace", "detail_surface"],
    signalLabels: ["schema_match", "response_latency", "rate_limit"],
    updatedAt: iso(-18),
  },
  {
    id: "driver-004",
    key: "document.summarizer",
    name: "文档整理器",
    category: "document",
    status: "ready",
    scope: "把采集到的证据整理成面向操作员的输出和回放材料。",
    description: "把浏览器和 HTTP 证据转成摘要、评分卡和可审批的总结。",
    safetyMode: "local_only",
    supportsWrite: true,
    sceneTypes: ["summary", "scorecard", "handoff_bundle"],
    signalLabels: ["output_contract", "coverage_score", "citation_density"],
    updatedAt: iso(-11),
  },
];

const runtimeEnvironmentAssessments: RuntimeEnvironmentAssessment[] = [
  {
    id: "assessment-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    executionEpisodeId: "episode-001",
    snapshotId: "snapshot-001",
    environmentKey: "recruiting:candidate_listing",
    sceneLabel: "前端平台候选人列表",
    sceneType: "candidate_listing",
    status: "aligned",
    confidence: 0.94,
    summary: "当前观察到的候选人卡片、岗位标签和详情入口，仍与现有受监督初筛计划保持一致。",
    observedEntities: [
      {
        kind: "candidate_card",
        label: "候选人卡片",
        entityId: "candidate-card-1",
        role: "result",
        confidence: 0.94,
        state: "visible",
        interactive: true,
        signals: ["listing_surface"],
        locator: { selector: "[data-candidate-card]" },
        attributes: { count: 8 },
      },
    ],
    affordances: [
      {
        kind: "link",
        label: "打开候选人详情",
        action: "navigate",
        target: "detail_page",
        confidence: 0.9,
        enabled: true,
        requiresConfirmation: false,
        signals: ["navigation_target"],
        locator: { selector: "a[data-open-candidate]" },
        metadata: {},
      },
    ],
    sceneProfile: {
      source: "browser",
      sceneType: "candidate_listing",
      interactionMode: "navigate",
      volatility: "low",
      authState: "clear",
      entityCount: 3,
      affordanceCount: 3,
      primaryTargets: ["候选人卡片"],
      signals: ["listing_surface", "well_observed_scene"],
      blockers: [],
      evidence: { observed_entity_kinds: ["candidate_card", "scorecard", "resume_evidence"] },
    },
    plannerGuidance: {
      posture: "verify",
      requiredCapabilities: ["search.discovery", "browser.navigator", "document.summarizer"],
      insertedCapabilities: ["browser.navigator"],
      preferredNextActions: ["在写入评分前，先确认候选人列表与岗位标签仍然一致。"],
      requiresSceneAssessment: true,
      requiresHumanReview: false,
      shouldCheckpoint: true,
      rationale: ["当前场景整体健康，但在正式抽取前仍应确认候选人列表布局。"],
    },
    capabilityKeys: ["search.discovery", "browser.navigator", "document.summarizer"],
    observedLabels: ["candidate_card", "scorecard", "resume_evidence"],
    affordanceLabels: ["open_candidate", "capture_notes", "record_observation"],
    driftSignals: [],
    recommendedActions: ["保持现有初筛编排继续可用。", "如果候选人评分结果依旧可靠，可在确认后提升为正式版本。"],
    updatedAt: iso(-14),
  },
  {
    id: "assessment-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    snapshotId: "snapshot-002",
    environmentKey: "recruiting:detail_surface",
    sceneLabel: "Jason Li 候选人详情",
    sceneType: "detail_surface",
    status: "drift_detected",
    confidence: 0.72,
    summary: "当前详情页仍可识别，但沟通记录被折叠进新的标签页里。",
    observedEntities: [
      {
        kind: "candidate_workspace",
        label: "候选人详情",
        entityId: "candidate-detail-1",
        role: "detail",
        confidence: 0.83,
        state: "partial",
        interactive: true,
        signals: ["listing_surface", "detail_surface"],
        locator: { selector: "[data-candidate-detail]" },
        attributes: { communication_tab_visible: false },
      },
    ],
    affordances: [
      {
        kind: "tab",
        label: "切换到沟通标签",
        action: "click",
        target: "message_thread",
        confidence: 0.76,
        enabled: true,
        requiresConfirmation: false,
        signals: ["navigation_target"],
        locator: { selector: "button[data-tab='messages']" },
        metadata: {},
      },
    ],
    sceneProfile: {
      source: "browser",
      sceneType: "detail_surface",
      interactionMode: "interact",
      volatility: "medium",
      authState: "clear",
      entityCount: 3,
      affordanceCount: 3,
      primaryTargets: ["候选人详情", "沟通标签"],
      signals: ["listing_surface", "detail_surface"],
      blockers: ["scene_needs_reassessment"],
      evidence: { observed_entity_kinds: ["candidate_workspace", "resume_evidence", "communication_log"] },
    },
    plannerGuidance: {
      posture: "recover",
      requiredCapabilities: ["browser.navigator", "document.summarizer", "api"],
      insertedCapabilities: ["browser.navigator"],
      preferredNextActions: [
        "重新确认沟通标签中的历史消息是否完整。",
        "在发送简历请求前插入人工确认点。",
      ],
      requiresSceneAssessment: true,
      requiresHumanReview: true,
      shouldCheckpoint: true,
      rationale: ["场景漂移说明规划器应先重新评估详情页结构，再继续推进沟通。"],
    },
    capabilityKeys: ["browser.navigator", "document.summarizer", "api"],
    observedLabels: ["candidate_workspace", "resume_evidence", "communication_log"],
    affordanceLabels: ["switch_tab", "capture_notes", "request_resume"],
    driftSignals: ["沟通记录被折叠进新标签。", "最近一次外联摘要被挪到了右侧面板。"],
    recommendedActions: ["在发送简历请求前插入场景评估检查点。", "下一版重规划优先重新恢复沟通上下文。"],
    updatedAt: iso(-10),
  },
];

const runtimeTemplates: RuntimeTemplate[] = [
  {
    id: "template-001",
    templateKey: "recruiting_frontend_screening",
    name: "前端岗位初筛版本",
    domain: "recruiting",
    status: "draft",
    version: 1,
    sourceTaskSpecId: "task-001",
    templateBody: { steps: runtimePlans[0].planBody.steps, checkpoints: runtimePlans[0].checkpoints },
    activationStrategy: {
      mode: "supervised_trial_first",
      requires_confirmation: true,
      governance: {
        episode_quality_band: "high",
        domain_pack_version: "1.1.0",
        trial_expectations: { requires_supervised_trial: true, requires_scene_assessment_for_browser: true },
      },
    },
    validationSummary: "已在受监督初筛中完成验证。",
    lastValidatedAt: iso(-65),
    createdAt: iso(-64),
    updatedAt: iso(-64),
  },
  {
    id: "template-002",
    templateKey: "recruiting_candidate_followup",
    name: "候选人沟通推进版本",
    domain: "recruiting",
    status: "active",
    version: 1,
    sourceTaskSpecId: undefined,
    templateBody: { steps: runtimePlans[1].planBody.steps },
    activationStrategy: {
      mode: "trial_first",
      governance: {
        episode_quality_band: "medium",
        domain_pack_version: "1.1.0",
        quality_gates: { requires_message_draft: true, requires_candidate_evidence: true },
      },
    },
    validationSummary: "用于候选人沟通推进的稳定版本。",
    lastValidatedAt: iso(-320),
    createdAt: iso(-320),
    updatedAt: iso(-320),
  },
];

const runtimePatches: RuntimePatch[] = [
  {
    id: "patch-001",
    title: "修正 Jason Li 沟通推进编排",
    patchKind: "execution_divergence",
    status: "pending_review",
    templateId: "template-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    proposedBy: "runtime",
    divergenceSummary: "在处理 detail_surface 时，试跑执行出现偏差。",
    rationale: "观测到的候选人详情结构与当前执行编排不一致。",
    patchBody: { operations: [{ op: "review_checkpoint", target: "detail_surface" }, { op: "insert_human_checkpoint", target: "capture_human_confirmation" }] },
    runtimeMetadata: {
      generatedFromEpisode: "episode-002",
      domain_pack_version: "1.1.0",
      episode_quality_band: "medium",
      plan_version: 1,
    },
    createdAt: iso(-18),
    updatedAt: iso(-18),
  },
];

const runtimeReplans: RuntimePlanReplanResult[] = [
  {
    id: "replan-001",
    taskSpecId: "task-002",
    baseExecutionPlanId: "plan-002",
    executionPlan: {
      id: "plan-002-r2",
      taskSpecId: "task-002",
      name: "Jason Li 沟通推进重规划 v2",
      mode: "trial",
      status: "proposed",
      version: 2,
      approvalState: "pending_review",
      planBody: {
        steps: [
          { id: "inspect_candidate_profile", capability: "browser" },
          { id: "open_message_history", capability: "browser" },
          { id: "draft_outreach_message", capability: "llm" },
          { id: "request_resume", capability: "document" },
        ],
        instruction: "重新评估候选人详情场景，再确认沟通记录并输出简历请求草稿。",
        domain: "recruiting",
      },
      environmentRequirements: { requires_browser: true, requires_network: true, scene_assessment_required: true },
      checkpoints: [
        { kind: "scene_assessment", label: "发送前先确认沟通标签结构" },
        { kind: "approval", label: "复用前先审查更新后的沟通编排" },
      ],
      runtimeMetadata: { compiler: "runtime_replanner", trigger: "scene_drift" },
      compiledFromPatchId: "patch-001",
      createdAt: iso(-8),
      updatedAt: iso(-8),
    },
    status: "proposed",
    trigger: "scene_drift",
    summary: "已插入详情页重新评估和沟通确认步骤，避免在结构漂移时直接发送简历请求。",
    compilerNotes: [
      "详情页漂移主要集中在沟通记录的读取方式。",
      "输出约定保持不变，因此只调整了确认步骤和检查点顺序。",
    ],
    recommendedCapabilityKeys: ["browser.navigator", "document.summarizer", "api"],
    environmentAssessment: runtimeEnvironmentAssessments[1],
    patch: runtimePatches[0],
    createdAt: iso(-8),
  },
];

const domainPacks: DomainPackRecord[] = [
  {
    key: "general",
    name: "内部通用能力",
    description: "仅作为 Recruit Agent 内部执行内核的通用支持，不再作为独立产品场景暴露。",
    version: "1.2.0",
    maturity: "beta",
    runtimeOnly: true,
    defaultCapabilities: ["analyze", "browser", "llm", "document"],
    sampleTasks: ["在人工监督下整理一次执行摘要。", "为演进审批生成一份风险说明。"],
    defaultConstraints: { requires_human_supervision: true },
    defaultOutputContract: { kind: "summary", format: "markdown" },
    templateKeys: ["general_supervised_trial", "patch_review_loop"],
    compilerHints: ["优先要求明确目标、审批策略和输出约定，而不是把它当成独立产品场景。"],
    qualityGates: { requires_goal: true, requires_output_contract: true, requires_approval_policy: true },
    sceneExpectations: ["当场景需要交互时，记录浏览器场景检查点。"],
    trialExpectations: { requires_supervised_trial: true, requires_scene_assessment_for_browser: true },
    templateCount: 2,
    activeTemplateCount: 1,
  },
  {
    key: "recruiting",
    name: "招聘 Agent",
    description: "围绕候选人发现、初筛、沟通推进和交接材料整理的 Recruit Agent 主场景。",
    version: "1.1.0",
    maturity: "beta",
    runtimeOnly: true,
    defaultCapabilities: ["browser", "search", "document", "llm", "api"],
    sampleTasks: ["找到候选人并完成评分。", "获取简历并整理招聘备注。"],
    defaultConstraints: { requires_human_supervision: true, respect_messaging_approval: true },
    defaultOutputContract: { kind: "candidate_bundle" },
    templateKeys: ["recruiting_trial_screening"],
    compilerHints: ["把招聘网站视为运行时场景，并保留外联和上传动作的审批边界。"],
    qualityGates: { requires_candidate_criteria: true, requires_output_contract: true, enforce_write_approval: true },
    sceneExpectations: ["浏览器场景应确认列表页、详情页和简历获取检查点。"],
    trialExpectations: { requires_supervised_trial: true, requires_scene_assessment_for_browser: true },
    templateCount: 1,
    activeTemplateCount: 0,
  },
];

const runtimeCompilerContract: RuntimeCompilerContract = {
  contractVersion: "runtime-task-compiler-v4",
  strategy: "llm_first_structured_semantic_compiler",
  fallbackStrategy: "none",
  promptAsset: "tasks/runtime_task_compiler.md",
  requiredFields: ["goal", "domain", "constraints", "success_criteria", "approval_policy", "output_contract"],
  optionalFields: ["inputs", "preferred_capabilities", "preferred_domains", "environment_requirements", "checkpoints", "step_outline", "compiler_notes"],
  invariants: [
    "开发阶段不预设任何固定网站接入。",
    "编译器必须先生成结构化任务契约，再进入执行。",
    "当 LLM 编译失败时，应显式报错，而不是静默降级。",
  ],
  qualityGates: [
    "目标、审批策略、成功标准和输出约定都必须具体。",
    "浏览器类执行编排必须生成场景检查点和环境要求。",
    "写入、同步、上传或本地命令动作必须保持审批感知。",
  ],
  repairPolicy: {
    maxAttempts: 1,
    fallback: "none",
    escalateToHumanOnCriticalGaps: true,
  },
  availableDomains: domainPacks,
  availableCapabilities: runtimeCapabilityDrivers,
};

export const desktopRuntimeMock: RuntimeWorkspaceData = {
  compilerContract: runtimeCompilerContract,
  domainPacks,
  taskSpecs: runtimeTasks,
  plans: runtimePlans,
  episodes: runtimeEpisodes,
  snapshots: runtimeSnapshots,
  capabilityDrivers: runtimeCapabilityDrivers,
  environmentAssessments: runtimeEnvironmentAssessments,
  templates: runtimeTemplates,
  patches: runtimePatches,
  replans: runtimeReplans,
};

export const desktopSyncBacklogMock: SyncBacklogItem[] = [
  {
    id: "sync-001",
    target: "intranet:candidate_bundle",
    entityType: "candidate_bundle",
    entityId: "cand-001",
    status: "pending",
    attemptCount: 2,
    protocolVersion: "2026-04-14",
    deliveryMode: "local_first",
    lastAttemptedAt: iso(-42),
    nextAttemptAt: iso(25),
    payloadSummary: "Mia Chen 的候选人资料包正在等待内网可用后再同步。",
    lastError: "上一次回放触发同步时，内网目标暂时不可用。",
    payload: {
      protocol_version: "2026-04-14",
      target: { kind: "intranet", base_url: "https://intranet.local", api_path: "/sync/runtime" },
    },
    targetMetadata: { kind: "intranet", api_path: "/sync/runtime" },
    updatedAt: iso(-42),
  },
  {
    id: "sync-002",
    target: "intranet:candidate_scorecard",
    entityType: "candidate_scorecard",
    entityId: "cand-001",
    status: "pending",
    attemptCount: 1,
    protocolVersion: "2026-04-14",
    deliveryMode: "local_first",
    lastAttemptedAt: iso(-18),
    payloadSummary: "Mia Chen 的候选人评分摘要正在等待同步。",
    payload: {
      protocol_version: "2026-04-14",
      target: { kind: "intranet", base_url: "https://intranet.local", api_path: "/sync/runtime" },
    },
    targetMetadata: { kind: "intranet", api_path: "/sync/runtime" },
    updatedAt: iso(-18),
  },
];

export const desktopSyncStatusMock: SyncStatusSnapshot = {
  enabled: false,
  mode: "local_only",
  remoteAvailable: false,
  protocolVersion: "2026-04-14",
  source: "desktop_app",
  target: { kind: "intranet", api_path: "/sync/runtime" },
  pendingCount: desktopSyncBacklogMock.length,
  syncedCount: 1,
  failedDeliveryCount: 1,
  deferredCount: 1,
  backlogTotal: 3,
  lastAttemptAt: iso(-18),
  lastSuccessAt: iso(-320),
  latestError: "内网同步未启用，因此同步积压继续保留在本地。",
  nextAttemptAt: iso(25),
  byStatus: { pending: 2, synced: 1 },
  recentErrors: ["内网同步未启用，因此同步积压会继续保留在本地。"],
};

export const desktopAgentQueueMock: AgentQueueItem[] = [
  {
    taskId: "task-queue-001",
    taskType: "initial_screening",
    priority: 180,
    status: "pending",
    attempts: 1,
    candidateId: "cand-001",
    workflowNodeId: "initial_screening",
    payload: { candidate_id: "cand-001", workflow_node_id: "initial_screening" },
    queueAudit: [
      { kind: "enqueued", at: iso(-26), status: "pending", priority: 180 },
      { kind: "returned_to_queue", at: iso(-18), attempts: 1, error: "scene drift detected during supervised retry" },
    ],
    createdAt: iso(-30),
    updatedAt: iso(-18),
  },
  {
    taskId: "task-queue-002",
    taskType: "request_resume",
    priority: 300,
    status: "completed",
    attempts: 0,
    candidateId: "cand-001",
    workflowNodeId: "resume_capture",
    payload: { candidate_id: "cand-001", workflow_node_id: "resume_capture" },
    queueAudit: [
      { kind: "enqueued", at: iso(-90), status: "pending", priority: 300 },
      { kind: "claimed", at: iso(-84), attempts: 0, lockedBy: "scheduler" },
      { kind: "completed", at: iso(-82), attempts: 0 },
    ],
    createdAt: iso(-90),
    updatedAt: iso(-82),
  },
];

export const desktopReplayMockByEpisode: Record<string, RuntimeEpisodeReplay> = {
  "episode-001": {
    episode: runtimeEpisodes[0],
    taskSpec: runtimeTasks[0],
    executionPlan: runtimePlans[0],
    snapshots: [runtimeSnapshots[0]],
    patch: null,
    template: runtimeTemplates[0],
    approval: {
      id: "approval-episode-001",
      targetType: "workflow_template",
      targetId: "template-001",
      title: "激活前端岗位初筛版本",
      status: "pending",
      requestedBy: "runtime",
    },
    diagnostics: [
      {
        id: "diag-001",
        label: "编译器已生成受监督试跑计划",
        detail: "系统选择了招聘 Agent 主场景，并要求在提升复用前先做人审。",
        at: iso(-72),
        tone: "positive",
      },
      {
        id: "diag-002",
        label: "浏览器探索已完成",
        detail: "这次运行已经抓取候选人列表，并在未发生漂移的情况下提取出首批候选人摘要条目。",
        at: iso(-66),
        tone: "positive",
      },
      {
        id: "diag-003",
        label: "回放已可确认",
        detail: "已经产出可复用的初筛版本草稿，等待桌面端确认。",
        at: iso(-64),
        tone: "warning",
      },
    ],
    notes: [
      "这次回放保持在预期的环境模型内。",
      "系统已为新版本生成一条仅保留在本地的同步积压记录。",
    ],
  },
  "episode-002": {
    episode: runtimeEpisodes[1],
    taskSpec: runtimeTasks[1],
    executionPlan: runtimePlans[1],
    snapshots: [runtimeSnapshots[1]],
    patch: runtimePatches[0],
    template: runtimeTemplates[1],
    approval: {
      id: "approval-episode-002",
      targetType: "workflow_patch",
      targetId: "patch-001",
      title: "审查 Jason Li 沟通推进修订建议",
      status: "pending",
      requestedBy: "runtime",
    },
    diagnostics: [
      {
        id: "diag-004",
        label: "候选人档案已采集",
        detail: "Jason Li 的基础档案和最近沟通摘要已顺利读取。",
        at: iso(-23),
        tone: "positive",
      },
      {
        id: "diag-005",
        label: "检测到候选人详情页漂移",
        detail: "系统观测到沟通记录被折叠进新标签，并提出了新的确认节点修订建议。",
        at: iso(-19),
        tone: "critical",
      },
      {
        id: "diag-006",
        label: "修订建议等待桌面审查",
        detail: "在操作员确认修订计划之前，这条修订建议会继续保留在队列里。",
        at: iso(-18),
        tone: "warning",
      },
    ],
    notes: [
      "在再次复用这个版本前，应先刷新详情页环境启发式。",
      "这次回放表明当前沟通推进版本在人工监督下仍可继续使用。",
    ],
  },
};
