export function translateUiToken(value: string, copy: (en: string, zh: string) => string): string {
  const table: Record<string, string> = {
    active: "已激活",
    approved: "已批准",
    archived: "已归档",
    awaiting_review: "等待审查",
    blocked: "阻塞",
    communicating: "沟通中",
    completed: "已完成",
    confirmed: "已确认",
    cooldown: "冷却期",
    critical: "严重",
    degraded: "已降级",
    degraded_review: "降级审查",
    discovered: "已发现",
    disabled: "已禁用",
    diverged: "已偏离",
    draft: "草稿",
    free: "空闲",
    guardrailed: "受护栏保护",
    healthy: "健康",
    held: "已占用",
    hr_review: "HR 审查",
    idle: "空闲",
    interview_scheduled: "已安排面试",
    local_only: "仅本地",
    neutral: "中性",
    offer: "Offer",
    openai_compatible: "OpenAI 兼容",
    passed_to_talent_pool: "已入人才库",
    paused: "已暂停",
    pending: "待处理",
    pending_communication: "待沟通",
    pending_resume: "待简历",
    pending_review: "待审查",
    positive: "正向",
    production: "生产",
    rejected: "已拒绝",
    replan_requested: "请求重规划",
    running: "运行中",
    scoring: "评分中",
    screening: "初筛中",
    stable: "稳定",
    success: "成功",
    synced: "已同步",
    team_review: "团队审查",
    trial: "试跑",
    warning: "警告",
    waiting_human: "等待人工",
    waiting_reply: "等待回复",
    workflow_patch: "工作流补丁",
  };
  return table[value] ?? value;
}
